### ISSUE TITLE
Archive not getting en-US + ja-JP?

### ISSUE THREAD

**Issue by jjbrunton** [crunchy-labs/crunchy-cli#158]
When running on Windows, I cannot seem to get the archive function to download both the english dub and the japanese audio on any of the shows. It appears to just default to ja-JP and not grab the english.

crunchy archive --skip-existing -l en-US -l ja-JP -o "E:\Anime\{series_name}\Season {season_number}\S{season_number}E{episode_number} {title}.mkv" https://www.crunchyroll.com/series/G4PH0WEKE/bluelock

**Comment by LetMeByte** [comment]
Please provide more information, the console output would be very helpful.

**Comment by SaeglopurHax** [comment]
I’ve recently stumbled upon a similar issue whilst trying to download Hi no Tori (Phoenix) dubbed. Every instance failed. The issue pertains mainly to downloading an anime in a specific language. In my case using both a- or l- to try and encode en-US audio has failed. I assumed perhaps the issue was with regional anime (of which Hi no Tori (Phoenix) is one), but that doesn’t seem to be the case. To test it, I tried a more popular and widespread, non-regional anime. My Hero Academia failed with a "my hero academia is not available with en-US audio" prompt. Help?
Here’s my log:
> `crunchy download -a en-US https://www.crunchyroll.com/series/GYNV9DP2R/my-hero-academia-dubs`
> `:: ✔ Logging in`
> `:: ✔ Parsed url 1`
> `:: → Series My Hero Academia (Dubs) is not available with en-US audio`
> `:: ✔ Skipping url 1 (no matching episodes found)`

> Please provide more information, the crunchy-cli version and the console output would be very helpful.
