### ISSUE TITLE
With some episodes i have problems with the download

### ISSUE THREAD

**Issue by Askadelion** [crunchy-labs/crunchy-cli#22]
With some episodes i have problems with the download, i get the error: 

```
=> Logged in
=> Failed to parse url 1
An error occurred: failed to get episodes: could not find any matching episode
```
Download in the debug mode:

```
[debug] Executing `archive` command with 1 arg(s)
[debug] Validating arguments
[debug] FFmpeg detected
[debug] Using following audio locales: de-DE, ja-JP
[debug] Using auto merge behavior
[debug] Using resolution 'best'
[debug] Logging in
[debug] Logged in with username ...
[debug] Logged in
[debug] Parsing url 1
[debug] Failed to parse url 1

An error occurred: failed to get episodes: could not find any matching episode
```

this error come at the folow episodes:
http://www.crunchyroll.com/de/skeleton-knight-in-another-world/episode-2-a-first-job-a-girls-wish-and-an-approaching-shadow-842578
http://www.crunchyroll.com/de/the-dawn-of-the-witch/episode-2-dont-call-me-a-traitor-842670

**Comment by ByteDream** [comment]
As fastest fix I recommend is using crunchyroll beta urls. These are always safe to use since the ids / names which are required by the api are fully contained by the url. Crunchyroll classic urls does not have these api friendly structure thus crunchyroll-go extracts the series and episode names from it and fires a search request after them. And this search request does not always return correct results, as we can see here.

Corresponding beta urls:
- [A first job a girl wish and an approaching shadow](https://beta.crunchyroll.com/de/watch/GVWU0Q2WN/a-first-job-a-girls-wish-and-an-approaching-shadow)
- [Don't call me a traitor](https://beta.crunchyroll.com/de/watch/G7PU4X423/dont-call-me-a-traitor)

This error never happened to me but I knew it would come up at some point...

**Comment by ByteDream** [comment]
Fixed in new release [v2.1.0](https://github.com/ByteDream/crunchyroll-go/releases/tag/v2.1.0).

**Comment by BraveSail** [comment]
Same here in lastest version.

The old episode url can be redirected to the new one with logged in, then we can find the new episode ID in the headers['location'], I think it's safer this way than search.

**Comment by Askadelion** [comment]
> 

The redirect is not immediately active with some episodes series it often takes hours or days until the redirect is active. So there is nothing for sure.

**Comment by ByteDream** [comment]
> Same here in lastest version.
> 
> The old episode url can be redirected to the new one with logged in, then we can find the new episode ID in the `headers['location']` which can used in the new api, I think it's safer this way than search.

Thanks for the suggestion, that's actually a very good and saver way than search!

**Comment by ByteDream** [comment]
> > 
> 
> The redirect is not immediately active with some episodes series it often takes hours or days until the redirect is active. So there is nothing for sure.

I can check for the redirect first and if it's active, use the redirect target beta url, and if it's not active, just use the search way.

**Comment by ByteDream** [comment]
Update: This does not work since crunchyroll uses cloudflare as its hoster (or as proxy to their servers). Cloudflare notices that this request does not come from a browser and thus, blocks the request.
This only happens here because, instead of calling an api endpoint, a "normal" front-end url gets called.

So the only solution to this stays to do not use classic urls at all :/
