### ISSUE TITLE
AMD hardware acceleration 

### ISSUE THREAD

**Issue by isthatmoe** [crunchy-labs/crunchy-cli#296]
can you add hevc_amf in ffmpeg-preset ?

**Comment by bytedream** [comment]
I added the options for amd hardware acceleration but I'm unable to test it because I don't have an amd gpu. Could you (or somebody else) verify that it's working? You can use the [pre-compiled binary](https://github.com/crunchy-labs/crunchy-cli/actions/runs/7661610150) (you have to scroll down a bit, to the `Artifacts` section and select the correct binary for your platform) of the change or compile the code yourself (from the [feature/amd-hwaccel branch](https://github.com/crunchy-labs/crunchy-cli/tree/feature/amd-hwaccel))
