### ISSUE TITLE
Subtitles different formattings

### ISSUE THREAD

**Issue by amarillodorado** [crunchy-labs/crunchy-cli#412]
**Describe the bug**
When downloading My Dress-Up Darling with the tool with the following command:
there are different formattings from the subtitles. I am already using the newest version.

**To Reproduce**
Download My Dress-Up Darling. Found it on episode 2 around 3:20 minute but it also happens on other videos.
Following Command:
crunchy-cli-v3.6.1-windows-x86_64.exe download -a ja-JP -s de-DE -o "{series_name}_S{season_number}E{episode_number}.mp4" ...
I use handbrake afterwards to compress the video and burn the subtitles.

**Expected behavior**
Always same subtitle formatting.

**Screenshots**
Downloaded version
![image](https://github.com/crunchy-labs/crunchy-cli/assets/145187060/30dca0e1-1d39-4ea9-918d-bda6977e5394)
Crunchyroll online version
![image](https://github.com/crunchy-labs/crunchy-cli/assets/145187060/96202d4f-9820-4135-90c7-eba85a3b6693)

Downloaded version
![image](https://github.com/crunchy-labs/crunchy-cli/assets/145187060/100afb60-835d-40e4-a977-541739ce8a04)
Crunchyroll online version
![image](https://github.com/crunchy-labs/crunchy-cli/assets/145187060/3f29eda6-b7c9-4ee9-94bb-70d3e897247a)

**Client (please complete the following information):**
 - OS: Windows
 - Version 3.6.1

**Comment by dok1100** [comment]
mp4 doesn't support ass subtitles, only text based.
That's the difference in the first and second picture.

I would use the achive instead of the download command. also --include-fonts if crunchy uses a different font.
Unfortunately there is also a typo in the ass file with v3.6.1. 

ScaledBorderAndShadows: 
actually it should be 
ScaledBorderAndShadow:

That's the difference in your third and fourth pictures.
You can use v3.5.2 or extract the subtitle, open it with a text editor and fix the typo yourself :)

**Comment by amarillodorado** [comment]
I just tried it with archive with 3.6.1 and now the subtitle from image 1 stand above of the japanese but it got very fat.
![image](https://github.com/crunchy-labs/crunchy-cli/assets/145187060/1b277b41-ab8a-431d-adb1-a52cfad8d8a5)
Actually if I use --force-hardsub it works only the font is not the same as on crunchyroll
![image](https://github.com/crunchy-labs/crunchy-cli/assets/145187060/9953d889-08a6-4685-8fd3-10e4741c616f)
![image](https://github.com/crunchy-labs/crunchy-cli/assets/145187060/e6c188e3-b4b2-4876-ad64-9e6f7b3cd55e)

**Comment by dok1100** [comment]
For me it doesn't look like yours in picture 1

can you try v3.5.2?
https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.5.2

**Comment by dok1100** [comment]
You have to do more for that. Because crunchyroll intended it to be bold in the subs.

-1 bold
0 not bold

![crs](https://github.com/crunchy-labs/crunchy-cli/assets/65904685/20bee3e5-c926-4863-80a9-e9a6986bbed5)

hmm, you can extract the subs with mkvextract and then change the -1 to 0 with a text editor.
You can then insert the edited subs into Handbrake.

crunchy-cli only downloads the ass subs and adds a line with ScaledBorderAndShadow: yes

**Comment by amarillodorado** [comment]
Thank you for your help. I tried it and it worked, I was already writing a script to automate it until I found out that if I specify in v3.5.2 that I want with archive -a ja-JP -s de-DE the formatting is right. Not sure why it works now but if it works I guess I am happy. I will test if it really works now.

**Comment by amarillodorado** [comment]
Nvm it didnt work (with the additional parameters), I think I did something wrong.
I am now doing it with a script (formatting) works fine so far. Thanks dok1100.

**Comment by bytedream** [comment]
The issue got fixed in [v3.6.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.6.2).

> Is there an option to get the subtitles to the normal size (not bold)?

There is no such option and I do not plan to add one. This is something for post-processing IMO
