### ISSUE TITLE
The other Competitor

### ISSUE THREAD

**Issue by imcrown** [crunchy-labs/crunchy-cli#435]
Hey can you also create the cli for Netflix , Prime Video, and others like Disney Hots star

**Comment by bytedream** [comment]
This downloader can only exist because Crunchyroll still has an endpoint that doesn't DRM encrypt the videos. Nearly every other streaming services does that and downloading / publishing software that downloads and decrypts DRM encrypted media is illegal or a legal gray area (depending how the software works).
An besides all this, I do not have the time for more projects of this kind
