### ISSUE TITLE
Download multiple episods

### ISSUE THREAD

**Issue by 002-sans** [crunchy-labs/crunchy-cli#54]
Heyy, I have a question. How to download multiple episodes (like 1,2 and 3 at same time), and how to download all episodes of a season ?

**Comment by ByteDream** [comment]
You can specify [filters](https://github.com/crunchy-labs/crunchy-cli/wiki/Cli#filter) on season urls.

This would download episode 1 - 3 of DARLING in the FRANXX for example:
```sh
$ crunchy download https://beta.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx[E1-E3]
```

**Comment by 002-sans** [comment]
thanks !

**Comment by 002-sans** [comment]
sorry but I just copy and paste that and I have this error:
`An error occurred: error while receiving format for Seule et solitaire: error for endpoint https://beta-api.crunchyroll.com/cms/v2/FR/M3/-/videos/streams?locale=fr-FR (403): invalid json response: invalid character '<' looking for beginning of value`

**Comment by 002-sans** [comment]
is it normal ?

**Comment by ByteDream** [comment]
This is probably because you're using a free account which causes that you do not have access to the full series.

For this particular case, the following should work:
```sh
$ crunchy download -a ja-JP -s fr-FR https://beta.crunchyroll.com/series/GY8VEQ95Y/darling-in-the-franxx[E1-E3]
```
This downloads the japanses dub with french subtitles. For DARLING in the FRANXX, free accounts have only access to the japanese audio and the `download` command without any extra flags tries to download every episodes in every available language (also the ones free accounts do not have access to). This may differ for other anime, so you have to check on the Crunchyroll website first to which languages you really have access to.
The audio for downloading can be specified with the `-a` flag, the subtitles with `-s`.

**Comment by ByteDream** [comment]
A proper error message telling exactly this would be a useful feature for a future release

**Comment by 002-sans** [comment]
ok, thank you so much !!
