### ISSUE TITLE
Cannot download when the system language is zh-CN

### ISSUE THREAD

**Issue by ltsj** [crunchy-labs/crunchy-cli#60]
**Describe the bug**
I have specified ja-JP to download but the local language will still be downloaded ，Then the above problem occurs.

**To Reproduce**
```
$ crunchy archive -l ja-JP https://www.crunchyroll.com/series/G9VHN91ZP/legend-of-mana--the-teardrop-crystal-[S1E1] -debug
➞ Failed to parse url 1
➞ An error occurred: failed to get episodes: error for endpoint https://beta-api.crunchyroll.com/cms/v2/FR/M3/crunchyroll/movies?movie_listing_id=G9VHN91ZP&locale=zh-CN&Signature=G9Z~3eRxH..... (400): Unsupported locale zh-CN
```

**Expected behavior**
I hope it can be downloaded in the specified language.

**Client (please complete the following information):**
 - OS: Debian 11
 - Version v2.3.5

**Comment by ArturiaPendragon** [comment]
On Windows : 

```
crunchy-v2.3.5_windows.exe archive -l ja-JP https://www.crunchyroll.com/series/G9VHN91ZP/legend-of-mana--the-teardrop-crystal-[S1E1] -debug
=> Parsed url 1
=> Legend of Mana -The Teardrop Crystal- Season 1
=>      1. Lapis-lazuli (première partie) » 1920x1080px, 23.97 FPS (S01E01)

=> Downloading episode `Lapis-lazuli (première partie)` to `Lapis-lazuli (première partie).mkv` (merging audio for additional formats)
=>      Episode: S01E01
=>      Audio: ja-JP
=>      Subtitle:
=>      Resolution: 1920x1080px
=>      FPS: 23.97

=> An error occurred: error while downloading: crypto/aes: invalid key size 424
```

**Comment by ByteDream** [comment]
> **Describe the bug** I have specified ja-JP to download but the local language will still be downloaded ，Then the above problem occurs.
> 
> **To Reproduce**
> 
> ```
> $ crunchy archive -l ja-JP https://www.crunchyroll.com/series/G9VHN91ZP/legend-of-mana--the-teardrop-crystal-[S1E1] -debug
> ➞ Failed to parse url 1
> ➞ An error occurred: failed to get episodes: error for endpoint https://beta-api.crunchyroll.com/cms/v2/FR/M3/crunchyroll/movies?movie_listing_id=G9VHN91ZP&locale=zh-CN&Signature=G9Z~3eRxH..... (400): Unsupported locale zh-CN
> ```
> 
> **Expected behavior** I hope it can be downloaded in the specified language.
> 
> **Client (please complete the following information):**
> 
>     * OS: Debian 11
> 
>     * Version v2.3.5

This error originates from Crunchyrolls poor adoption of Chinese (`zh-CN`). A temporary fix for this is to prefix your command with `LANG=en_US`. I look into it if / how I can fix it the best way.

Example with the `LANG=en_US` prefix:
```sh
$ LANG=en_US crunchy archive -l ja-JP https://www.crunchyroll.com/series/G9VHN91ZP/legend-of-mana--the-teardrop-crystal-[S1E1]
```

---

> On Windows :
> 
> ```
> crunchy-v2.3.5_windows.exe archive -l ja-JP https://www.crunchyroll.com/series/G9VHN91ZP/legend-of-mana--the-teardrop-crystal-[S1E1] -debug
> => Parsed url 1
> => Legend of Mana -The Teardrop Crystal- Season 1
> =>      1. Lapis-lazuli (première partie) » 1920x1080px, 23.97 FPS (S01E01)
> 
> => Downloading episode `Lapis-lazuli (première partie)` to `Lapis-lazuli (première partie).mkv` (merging audio for additional formats)
> =>      Episode: S01E01
> =>      Audio: ja-JP
> =>      Subtitle:
> =>      Resolution: 1920x1080px
> =>      FPS: 23.97
> 
> => An error occurred: error while downloading: crypto/aes: invalid key size 424
> ```

This is, once again, an error on the Crunchyroll servers. Video streams are encrypted with a key which differs for every episode and Crunchyroll fails to deliver the decryption key for the episode you want to download. Waiting is the only option here, and hoping that this issue is fixed soon.

Crunchyroll provides two ways how videos can be streamed / downloaded, [HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming) and [DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP). While crunchyroll.com uses `DASH` and it works flawless with this episode, crunchy-cli uses `HLS` (which caused this issue). The decision to use `HLS` for crunchy-cli was made because it is widely used and the protocol is way cleaner than `DASH`. Just in case you were wondering why it's working on the website but not here.
As far as I can see this error only occurs on this one episode, so I don't see an urgent need to change how to receive video stream. But I might add a fallback to `DASH` if `HLS` does not work in the future.

**Comment by ByteDream** [comment]
Locale used can be manipulated with the `--lang` flag beginning with release [v2.3.6](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v2.3.6).
